# Generated by Django 4.0.1 on 2022-02-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_egn_alter_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('Software developer', 1), ('QA Engineer', 2), ('DevOps', 3)], default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, default='NO NAME', max_length=40, null=True),
        ),
    ]
